services:
  - type: web
    name: inventory-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
