services:
  - type: web
    name: inventory-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    rootDir: .
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
